version: "v1"
project: "communicat"
services:
  frontend:
    node:
      image: "frickreich/communicat:0.1"
      instances: 1
      mem: 512
      domain: communicat.sloppy.zone
      port: 3000
      env:
        - MONGODB_URI: "mongodb://mongodb.backend.frickreich/starter"
        - ROOT_URL: "https://communicat.sloppy.zone"
        - MONGO_INITDB_ROOT_USERNAME: "admin"
        - MONGO_INITDB_ROOT_PASSWORD: "test"
      dependencies:
        - "../backend/mongodb"
    mongo:
      image: 'mongo-express'
      instances: 1
      mem: 256
      port: 8081
      env:
        - ME_CONFIG_MONGODB_SERVER: "mongodb.backend.communicat"
        - ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
        - ME_CONFIG_MONGODB_ADMINPASSWORD: "test"
        - ME_CONFIG_BASICAUTH_USERNAME: "admin"
        - ME_CONFIG_BASICAUTH_PASSWORD: "test"
  backend:
    mongodb:
      image: "mongo"
      cmd: "mongod --smallfiles"
      instances: 1
      mem: 512
      volumes:
        - path: "/data/db"
        - path: "/data/configdb"
