version: "v1"
project: "communicat"
services:
  frontend:
    node:
      image: "frickreich/communicat:latest"
      instances: 1
      mem: 512
      domain: communicat.sloppy.zone
      port: 3000
      env:
        - MONGODB_URI: "mongodb://mongodb.backend.communicat"
        - ROOT_URL: "https://communicat.sloppy.zone"
        - MONGO_INITDB_ROOT_USERNAME: "admin"
        - MONGO_INITDB_ROOT_PASSWORD: "test"
      dependencies:
        - "../backend/mongodb"
    mongoexpress:
      image: "mongo-express:latest"
      instances: 1
      mem: 256
      port: 8081
      env:
        - ME_CONFIG_MONGODB_SERVER: "mongodb.backend.communicat"
        - ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
        - ME_CONFIG_MONGODB_ADMINPASSWORD: "test"
        - ME_CONFIG_BASICAUTH_USERNAME: "admin"
        - ME_CONFIG_BASICAUTH_PASSWORD: "test"
    cloud:
      image: "owncloud:10.0.3"
      domain: communicat.sloppy.zone
      instances: 1
      port: 85
      mem: 1024
      
  backend:
    mongodb:
      image: "mongo"
      cmd: "mongod --smallfiles"
      instances: 1
      env:
        - MONGO_INITDB_ROOT_USERNAME: "admin"
        - MONGO_INITDB_ROOT_PASSWORD: "test" 
      mem: 512
      volumes:
        - path: "/data/db"
        - path: "/data/configdb"
