version: '2'
services:

  web:
    image: frickreich/communicat
    ports:
      - "80:3000"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cpmmunicat

  redis:
    image: "redis:alpine"

  mongo:
    image: mongo:4.0
    command: mongod --smallfiles
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - all

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - all

networks:
  all:
