version: '2'
services:

  web:
    image: frickreich/communicat:0.1
    ports:
      - "80:3000"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/communicat"

  mongo:
    image: mongo:3
    command: mongod --smallfiles
    networks:
      - all

  mongoexpress: 
    image: mongo-express:latest
    networks:
      - all

networks:
  all: